### ISSUE TITLE
No way to add configuration snippets.

### ISSUE THREAD

**Issue by sjjf** [zehweh/puppet-netplan#10]
At the moment it looks like there's no way to add new configuration snippets to the overall netplan config - you get a single static definition via hiera, or you get a single definition at the point you define the class, but there's no way to add more configuration at a later point or anywhere else in the manifest.

I think, given the way that netplan works with later files in the config amending previous ones, it should be entirely possible to support this kind of thing - simply adding a new file with the desired amendments, which sorts later and hence overrides and amends the earlier config.

I'd suggest implementing this as a defined type, taking a priority value that would specify the ordering and then taking the same config hash that the main class takes, and would then output a file named `/etc/netplan/<priority>-<title>.yaml`.

I'll see if I can find time to write a pull request implementing this myself, but I don't know when I'll be able to get to it.

**Comment by zehweh** [comment]
Thanks for you interest in this project.

Yes, this should be possible. But I don't see any need for this. The whole purpose of this module is to configure netplan using hiera. And with hiera you can do all the things you would do using additional files like `/etc/netplan/<priority>-<title>.yaml`.

Or do I miss something here? Can you please provide me with a use case?
