### ISSUE TITLE
Exec['netplan_apply'] notifies on any change with $netplan_apply=false

### ISSUE THREAD

**Issue by Andor** [zehweh/puppet-netplan#2]
Right now `Exec['netplan_apply']` executes on any change in the class because of class updates.

There are two options for avoiding it:
1. move this exec to the special class (e.g. `netplan::apply`) and notify this class. Notify of class `netplan` will not affect it.
2. make this exec optional and not create it if `$netplan_apply=false`.

**Comment by zehweh** [comment]
Closing this issue.
