### ISSUE TITLE
How to support extensive customer routes

### ISSUE THREAD

**Issue by goetzk** [zehweh/puppet-netplan#20]
Hi,
For $reasons we have various groups of servers with dozens of routes, which can change often enough that hard coding the list is going to result in issues.
Our current solution is a template which lips a list of addresses and inserts appropriate entries.
Looking at the code it doesn't look like the routes can be supplied separately or augmented dynamically.
I am looking at hacking in an extra routes option I can feed more dynamic data to, but wondered if there was an existing way - or an upstream acceptable change - I could leverage.
 Thanks,
Karl

**Comment by zehweh** [comment]
Hi Karl,

sorry for the long wait.
Unfortunately, I don't know of any way to address your problem.

Since nobody else responded to your issue, I'm going to close it for now. Feel free to reopen it if needed.

chris
