### ISSUE TITLE
can't configure certain point-to-point gre tunnels

### ISSUE THREAD

**Issue by jsfrerot** [zehweh/puppet-netplan#24]
The following gre configuration isn't handled properly by the netplan module:

```  tunnels:
    tun1:
      mode: "gre"
      local: "1.1.1.1"
      remote: "2.2.2.2"
      ttl: 255 # required when we need to route traffic through the tunnel
      addresses:
        - "172.31.0.1/32"
      mtu: 1440
      routes:
        - to: "172.31.0.2/32"
          scope: "link"
```
There are 3 issues with the needed configuration.
1- support for "ttl" value isn't present
2- on link route isn't supported as the "via" param is considered mandatory.
3- the "scope" value is ignore and not provided to netplan config file.

**Comment by jsfrerot** [comment]
proposed the following pull request: [https://github.com/zehweh/puppet-netplan/pull/25](url)

**Comment by zehweh** [comment]
Your PR has been merged.
